_format_version: "3.0"
_transform: true

services:
  - name: user-service
    url: http://user-service:3001
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: prometheus
        config:
          per_consumer: false

  - name: product-service
    url: http://product-service:3002
    plugins:
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
      - name: prometheus
        config:
          per_consumer: false

  - name: order-service
    url: http://order-service:3003
    plugins:
      - name: rate-limiting
        config:
          minute: 150
          hour: 1500
      - name: prometheus
        config:
          per_consumer: false

routes:
  - name: user-routes
    service: user-service
    paths:
      - /api/users

  - name: product-routes
    service: product-service
    paths:
      - /api/products

  - name: order-routes
    service: order-service
    paths:
      - /api/orders

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: prometheus
    config:
      per_consumer: false
